version: "3.8"

services: 
  mqtt:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
      args:
        - MQTT_USERNAME=${MQTT_USERNAME}
        - MQTT_PASSWORD=${MQTT_PASSWORD}
    container_name: homemonitor-mqtt
    ports:
      - '1883:1883'
      - '9003:9003'
    volumes:
      # - /mosquitto/config
      - /mosquitto/data
      - /mosquitto/log
    restart: unless-stopped

  influxdb:
    build: ./influxdb
    # image: influxdb:alpine
    container_name: influxdb
    # ports:
    #   - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      # INFLUXDB_DB: ${INFLUXDB_DATABASE}
      - DEFAULT_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
    restart: unless-stopped

volumes:
  influxdb_data:
