version: "3.8"

services: 
  mqtt:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
      args:
        - MQTT_USERNAME=${MQTT_USERNAME}
        - MQTT_PASSWORD=${MQTT_PASSWORD}
    container_name: homemonitor-mqtt
    ports:
      - '1883:1883'
      - '9003:9003'
    volumes:
      # - /mosquitto/config
      - /mosquitto/data
      - /mosquitto/log
    restart: unless-stopped

