# This is a basic workflow to help you get started with Actions

name: Stack-Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install mosquitto
      - name: Install mosquitto
        run: sudo apt update && sudo apt-get install -y mosquitto

      # run mosquitto in verbose mode
      - name: ReStart mosquitto
        run: |
          sudo service mosquitto stop
          sudo systemctl stop mosquitto.service
          mosquitto -v

      # build and run stack
      - name: Compose up
        run: docker-compose -f "docker-compose.yml" up -d --build

      # check that mosquitto can publish a message
      - name: Mosquitto publish
        run: mosquitto_pub -h 127.0.0.1 -p 1883 -u mqtt -P password -t mig-stack/messages -m "hello runner" -d
